### ISSUE TITLE
Legend is not complete

### ISSUE THREAD

**Issue by gorgobacka** [simra-project/dataset#2]
I'm playing a bit around with the data and want to perform some analysis. I'm really interested to look more in detail.

Unfortunately, the legend is not complete and ends with:

    co2: The co2 savings of rides a user has uploaded by not driving a car
    0,1,...,23: The distribution of rides through the hours in a day. If a ride is from 2:34pm to 3:10pm, the values at 2 and 3 will be increased by 0.5
    behaviour: 

**behaviour** is not described. I expect it belongs to "Wie oft halten Sie sich an die Verkehrsregeln?". But What are the possible values and what's there meaning.

**numberOfScary** is completely missing.

**Comment by gorgobacka** [comment]
And can you please indicate the unit of measurement?

Is the "duration" specified in seconds and I expect the "distance" is specified in meter?

If that's the case, some durations and distances are quite large.

**Comment by selphiron** [comment]
I updated the readme and legend. Thanks! 
behaviour: How much the user follows the traffic rules. 0 - 5, where 0 is "never" and 5 is "always"
numberOfScary: The number of uploaded incidents that were labeled as scary by the user

Unit of duration: milliseconds
Unit of waitedTime: seconds
Unit of distance: meters

Yes, some durations and meters are indeed quite large.

**Comment by gorgobacka** [comment]
Thanks a lot for the fast reply and for fixing the legend. Now it's more clear to me.

> Yes, some durations and meters are indeed quite large.

Are you sure that this is correct?
