### ISSUE TITLE
Same format for all profiles

### ISSUE THREAD

**Issue by gorgobacka** [simra-project/dataset#3]
While looking at the files for profiles, I saw that their structure is not uniform and differ from each other. Sometime the header is missing and sometimes the header is much shorter.

For data analysis, it would be much better, if all files have the same structure. Is it possible to provide the dump for the profiles in that way?

**Comment by selphiron** [comment]
We had new columns added over time. Apart from the added headers like behaviour, the order of the header is always the same. Is that still a problem?

**Comment by gorgobacka** [comment]
It's not a big deal for me. I adapted the parser to deal with the different formats.

But on the long run, it would be better to have the same format for all files. Otherwise the legend fits only to subset of files and people need to figure it out before they can start analysing the dataset.
