### ISSUE TITLE
Please provide an updated dataset

### ISSUE THREAD

**Issue by gorgobacka** [simra-project/dataset#4]
Is it possible to provide an updated dataset? The current data is 5 and 6 month old. I'm specially interested in the regions that do not belong to Berlin.

When I checked the profiles, I'm  wondering, why there are only a few regions present. Is that really the case? I expected to see more.

Btw: the "UNKNOWN" dataset contains a large percentage of profiles from Berlin.

"UNKNOWN" dataset (the numbers indicate the sum of profiles for that region):

    Berlin                            97
    Bern                               9
    London                             1
    Other                             11
    Pforzheim/Enzkreis                 1
    Please Choose (default value)    196

**Comment by selphiron** [comment]
Yes, new data are on their way :)

**Comment by gorgobacka** [comment]
Thanks. I'm looking forward to it. :)

**Comment by gorgobacka** [comment]
Today, I looked into the rides (everything that is published at the moment from Dec. 2019) more in detail.

But I'm wondering, is the data complete? Because I can't find rides submitted by myself. I filtered _all_ rides based on location and visualized them on a map. And due to the fact, that for my city there are only a few rides. I should see them clearly.

Unfortunately, my mobile phone containing my rides from last year is broken and I can't support my feeling with concrete data.

**Comment by gorgobacka** [comment]
@selphiron 
Do you have any ETA for the updated datasets?
Or do you have any news regarding the missing rides?

**Comment by selphiron** [comment]
The updates are here. Sorry for the delay. We were looking for a new platform.
We can't upload everything yet due to privacy reasons. We upload a region only if we have enough rides per day, so that single users are difficult to pin out. 
However, we work on a feature that allows to export and import rides from the app. In the iOS-version, rides can be exported already.

**Comment by gorgobacka** [comment]
Thanks for the explanations.
