### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by FelizCoder** [simra-project/dataset#6]
Hello,

the last data was uploaded in 10.2022. According to the dashboard the count of records is still increasing. Will you continiue to upload the data into this dataset or was the Database moved somwhere else?

All the best
Felix

**Comment by selphiron** [comment]
I updated the dataset. Due to GitHub's limitations, we cannot upload the whole dataset to GitHub. That is why we intend to upload only the data from the previous whole month for Berlin. We will upload the whole dataset for Berlin to depositonce (see the readme) once - twice a year.
